# Generated by Django 3.1.1 on 2020-09-17 08:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'elxr_accounts_list',
            },
        ),
        migrations.CreateModel(
            name='conquest_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('sub_process', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('questions_count', models.CharField(max_length=10)),
                ('passing_score', models.CharField(max_length=100)),
                ('max_attempts', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_conquest_list',
            },
        ),
        migrations.CreateModel(
            name='conquest_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquest_id', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_conquest_questions',
            },
        ),
        migrations.CreateModel(
            name='conquest_recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('conquest_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('attempts', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'elxr_conquest_recipients',
            },
        ),
        migrations.CreateModel(
            name='conquest_recipients_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquest_id', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('attempt_no', models.CharField(max_length=10)),
                ('answers', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elxr_conquest_recipients_answers',
            },
        ),
        migrations.CreateModel(
            name='projects_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'elxr_projects_list',
            },
        ),
        migrations.CreateModel(
            name='question_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_option', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('question_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elxr_question_details',
            },
        ),
        migrations.CreateModel(
            name='question_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=10)),
                ('media_type', models.CharField(max_length=100)),
                ('media_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'elxr_question_list',
            },
        ),
        migrations.CreateModel(
            name='sub_process_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('sub_process_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_sub_process_details',
            },
        ),
        migrations.CreateModel(
            name='sub_process_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_process_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'elxr_sub_process_list',
            },
        ),
        migrations.CreateModel(
            name='update_conquest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(max_length=100)),
                ('conquest_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_update_conquest',
            },
        ),
        migrations.CreateModel(
            name='update_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('sub_process', models.CharField(max_length=50)),
                ('update_type', models.CharField(max_length=50)),
                ('update_source', models.CharField(max_length=50)),
                ('update_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_update_details',
            },
        ),
        migrations.CreateModel(
            name='update_recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('update_id', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=100)),
                ('ack_status', models.CharField(max_length=20)),
                ('ack_comment', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'elxr_update_recipients',
            },
        ),
        migrations.CreateModel(
            name='update_source_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_source_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_update_source_list',
            },
        ),
        migrations.CreateModel(
            name='update_type_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'elxr_update_type_list',
            },
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'elxr_user_details',
            },
        ),
    ]
